export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const THONG_TIN_NGUOI_DUNG = 'THONG_TIN_NGUOI_DUNG';
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = 'LAY_DANH_SACH_LOAI_NGUOI_DUNG';
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_SEARCH = 'LAY_DANH_SACH_LOAI_NGUOI_DUNG_SEARCH';